### ISSUE TITLE
Problem with "CONT"

### ISSUE THREAD

**Issue by heasm66** [pdxiv/PerlScott#11]
There is a problem with "CONT". If I have an action with more than 4 instructions it's split with 3 instructions + "CONT" in the action and the rest is pushed to an "occur 0%" directly after with the rest of the instructions.

Example:
```
ident 1
version 416
wordlen 3
maxload 6
lighttime 125
unknown1 5953
unknown2 819
start forest
treasury forest

room forest "forest"

action SAY HEL
	set_flag 2
	set_flag 2
	set_flag 2
	set_flag 2
	print "Hello Sailor!"
```
Plays like this (with debug):
```
I'm in a forest


DEBUG: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
DEBUG: 0 0 0 0 0 0 0 0 125
Tell me what to do
say hello

DEBUG: Action 0. verb 2 (SAY), noun 7 (HEL) (CONT 0), ""
DEBUG: Condition 0 Par with parameter 2
DEBUG: Condition 0 Par with parameter 2
DEBUG: Condition 0 Par with parameter 2
DEBUG: Condition 0 Par with parameter 0
DEBUG: Condition 0 Par with parameter 0
DEBUG: Command code 6 SETz
DEBUG: Command code 6 SETz
DEBUG: Command code 6 SETz
DEBUG: Command code 21 CONT
DEBUG: 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
DEBUG: 0 0 0 0 0 0 0 0 125
Tell me what to do
```
If you try adventure #3 "Mission Impossible" and frisk the dead saboteur he never drops the map, the case or the leaflet and you never get the message!

Source (decompiled with scottkit):
```
action FRI SAB when present saboteur and !exists envelope
	drop envelope
	drop yarn
	drop maintance
	continue

occur 0%
	drop map
	drop case
	print "Something fell to the floor."
	drop leaflet
	comment "FRISKING SABOTEUR"
``` 
Show like this in perlscott:
```
Tell me what to do
fri sab

Tell me what to do
look

I see nothing special.
I'm in a yellow room. Visible items here:
Yellow door with tv camera over it. Empty manila envelope. Piece of yarn. Picture of saboteur stamped -window maintance-. Dead saboteur.
Obvious exits: SOUTH

Tell me what to do
```

**Comment by heasm66** [comment]
I think I found the problem. The $cont_flag get zeroed in the subroutine "run_action", both on line 1213 & 1231. If I remove those and instead clear the flag after "execute_command on line 1226 it works.

I noticed another problem though. If you have more than 7 instructions that solution won't work. If I instead change the flag to a counter that increases on line 462, and decreases on the new line after 1226 it works.

I get the same behaviour now both in PerlScott, ScottFree and ScottKit. I'm enclosing the changed file and some testfiles.
[modified_perlscott_and_testfiles.zip](https://github.com/pdxiv/PerlScott/files/4740867/modified_perlscott_and_testfiles.zip)

**Comment by pdxiv** [comment]
Thanks a lot for the bug report! I'll make sure it's integrated, or if you want to make a pull request, that works too.

**Comment by heasm66** [comment]
Maybe I was a bit quick. The problem still remains in "Mission Impossible"...

**Comment by pdxiv** [comment]
The problem seems to be with "Actions", and not "Occurrences". The following mockup game file in ScottKit format illustrates this:
```
ident 3
version 306
wordlen 3
maxload 7
lighttime 10000
unknown1 5963
unknown2 681
start "eastroom"
treasury VOID

# ROOMS

room VOID ""

room "eastroom" "east room"
	exit west westroom

room "westroom" "west room"
	exit east "eastroom"

# ITEMS

item "sign" "Sign with the text:
type FRI SAB"
	at "eastroom"

item envelope "Empty manila envelope"	
	nowhere

item saboteur "Dead saboteur"	
	at "eastroom"

# ACTIONS

action FRI SAB when present saboteur and !exists envelope
	print "action 1"
	continue

occur 0%
	print "action 2"

occur 0%
	print "action 3"

# OCCURRENCES

occur 100%
	print "occur 1"
	continue

occur 0%
	print "occur 2"

occur 0%
	print "occur 3"
```
Actions differ from Occurrences in that processing of the action/occurrence list stops after an Action entry successfully executes. This logic needs to be altered.

**Comment by heasm66** [comment]
Not every item is "gettable". If you test Adv #3 and move west, west from your starting point and try to pick up the pail it'll fail.

I think it's the line 1254 that is the problem because if I remove that line everythink seems to work.
```
if ( $word_action_done == $TRUE ) { return 1; }
```
I'm of course not certin what this line is there for so removing it might cause other problems...
