### ISSUE TITLE
Condition func "-ANY" (11) is same as "ANY" (10) 

### ISSUE THREAD

**Issue by heasm66** [pdxiv/PerlScott#16]
In condition_function the definitions for 10-"loaded (ANY)" and 11-"!loaded (-ANY) is the same. I think 11 should start with $result = TRUE and become FALSE if player has something in his inventory.

**Comment by pdxiv** [comment]
Thanks for the report. Do you mean that the behavior is wrong, or that the code doesn't follow what the original TRS-80 Basic code does, or that the code should be simplified?

I verified that the behavior is correct with the following ScottKit game file:
```text
room chamber "square chamber"

item rock "rock"
	called ROC

action LOAD STATUS when !loaded
	print "I'm not loaded with anything"

action LOAD STATUS when loaded
	print "I'm loaded with stuff!"
```

**Comment by heasm66** [comment]
Sorry. My mistake. I missed (!) in the return-statement from code 11. Everything is working and correct. I close this issue.
