### ISSUE TITLE
In some games, the display of exits can be truncated.

### ISSUE THREAD

**Issue by auraes** [pdxiv/PerlScott#2]
You use the directional words in the vocabulary table to display the exits but, sometimes, these words are truncated as in the Scott Adams Voodoo Castle game.

>I'm in a chapel. Visible items here: 
Closed Coffin. 
Obvious exits: NOR SOU EAS WES

`"AUT"
"ANY"
"GO"
"NOR"
"*ENT"
"SOU"
"*WAL"
"EAS"
"*CLI"
"WES"
"*RUN""AUT"
"ANY"
"GO"
"NOR"
"*ENT"
"SOU"
"*WAL"
"EAS"
"*CLI"
"WES"
"*RUN"
"UP"
"."
"DOW"
"UP"
"."
"DOW"`

**Comment by pdxiv** [comment]
Thanks! The reason for this behavior, is that this is how the original TRS-80 Basic engine from 1978 handled the directional nouns.

Probably, the more modern versions of the engine had these words hard-coded in the engine. What needs to be done, is to add the words `NORTH`, `SOUTH`, `EAST`, `WEST`, `UP` and `DOWN` to the code.

I'm a bit uncertain about upper/lower case. Should it look like `NORTH`, `north` or `North` when it's printed out in the room description?

**Comment by auraes** [comment]
I don't know what the English grammar says in this case, but with the 8.5 driver of the TRS-80, the letters are all capitalized.

**Comment by pdxiv** [comment]
This has now been added in the latest commit: https://github.com/pdxiv/PerlScott/commit/aaad23908f7469838c830b853a9d3e5093fcf8c7

Thanks again for the issue report!
