### ISSUE TITLE
Title is always "*** Welcome to Adventure Land. (# 4.6) ***"

### ISSUE THREAD

**Issue by auraes** [pdxiv/PerlScott#4]
Whatever the game, the title is always "*** Welcome to Adventure Land. (# 4.6) ***", this can be confusing. With the TRS-80 8.5 driver, the header is:
`* ADVENTURE * (Version:8.5) Adventure number:1 Version:4.16`
I guess "ADVENTURE" is the name of the driver for all games. Maybe it's better to replace
 `*** Welcome to Adventure Land. (# 4.6) ***`
with 
`*** Welcome to Adventure ***`?

**Comment by pdxiv** [comment]
I looked up Pirate Adventure in Byte and the driver still said `Welcome to Adventure Land. (#4.6)`. Not sure if `Adventure Land` or `Adventure` was an actual name of the driver or some name that just stuck after the initial game.

Perhaps the best things would be to just remove the "Welcome" line completely, to reduce confusion, or perhaps just change it to `     ***   Welcome ***`. If anything, the Perl driver should be called `PerlScott`, and even that seems unnecessary to type out. If you ran the program already, it should be obvious enough :)

What do you think?

**Comment by auraes** [comment]
I said "driver" but the good word seems to be "interpreter" (my English is so bad!)
In Byte, p. 192, Adams says: Adventure interpreter (and there's an Adventure editor.)
So, "Adventure" seems to be the name of the interpreter/editor and 4.6 the version of it, but it's the word "land" that is confusing.
Do what you want, anyway, it's a detail.

**Comment by pdxiv** [comment]
Good to know! If Scott Adams uses the word "interpreter", then that's **probably** the right word for it. I (erroneously) alternate between saying "interpreter", "engine" and "driver" randomly :)

Changed the welcome line to simply read `*** Welcome ***`: https://github.com/pdxiv/PerlScott/commit/d6e07d7d86269d23e3d067998517b3d86dfae5e1

As always, thanks for the contribution! Let me know if you're doing anything interesting with it, or if you're thinking of using it for anything interesting.
