### ISSUE TITLE
Wrong array name In basicinterpreter.bas line 470 

### ISSUE THREAD

**Issue by auraes** [pdxiv/PerlScott#7]
In basicinterpreter.bas, line 470: 
`470 F1=IA(LL)=RORIR(LL)=-1:GOTO550`
It's not IR(LL) but IA(LL).

**Comment by auraes** [comment]
There are also errors in lines: 720, 900, 1260, 1170
(Beware, there are sometimes several errors per line.)

**Comment by auraes** [comment]
Line 1300, 590, 250, 120, 80 too. I don't give the answers and let you search a little...

**Comment by auraes** [comment]
And 1300 too!

**Comment by pdxiv** [comment]
Thanks again for the issue report!

You seem to have a thorough understanding of the issues at hand. Would you mind providing a pull request? I don't mind performing the required changes, if you're too busy or or whatever, of course :)

**Comment by auraes** [comment]
I'm not sure I understand much about github: add, commit and push, that's about all I can do!
I will make the corrections on the basicinterpreter.bas file and I will send it to you (It will be easier for me.)

**Comment by pdxiv** [comment]
Well, we can do it in two different ways:
1. I add your user as a collaborator to the repository, and you can push what you want.
2. You can make your own fork of the repository (https://help.github.com/articles/fork-a-repo/), and when you're done with your changes to your fork, you can log a pull request,     (https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

Does any of these work well for you? Which one is best, if so?

**Comment by pdxiv** [comment]
Thanks again. Corrections have been made to the basic listing on lines 80, 120, 140, 250, 470, 590, 720, 1170, 1260, 1300, so far. Probably some more errors remain, and i'll need to go through it in more detail in the future. Corrected in: 878c0a28ed0f6aef6236da8014623e4bfdd52a7a
