### ISSUE TITLE
Line Feed (LF, 0A) and Carriage Return(CR, 0D) in Basic strings.

### ISSUE THREAD

**Issue by auraes** [pdxiv/PerlScott#8]
In TRS-80 Basic:
```
10 PRINT"PARLER-VOUS FRANÇAIS ?"
20 PRINT"PARLER-VOUS
 FRANÇAIS ?"
```

Text output line 10:

> PARLER-VOUS FRANÇAIS ?

Text output line 20 (There's a LF after PARLER-VOUS)

> PARLER-VOUS
> FRANÇAIS ?

But in basicinterpreter.bas, you don't reproduced the LF in strings as in the original Basic source code. Take a look at line 70:
```
PRINT"TO FIND OUT WHAT YOU'RE CARRYING YOU MIGHT SAY: TAKE INVENTORY
TO GO INTO A HOLE YOU MIGHT SAY: GO HOLE
TO SAVE CURRENT GAME: SAVE GAME"
```

Output seems to be different from this:
```
PRINT"TO FIND OUT WHAT YOU'RE CARRYING YOU MIGHT SAY: TAKE INVENTORY TO GO INTO A HOLE YOU MIGHT SAY: GO HOLE TO SAVE CURRENT GAME: SAVE GAME"
```

Am I clear ? (But maybe I'm wrong.)

**Comment by pdxiv** [comment]
I corrected the string with newline on line 70 in commit bacd771205f9cce888f432fe0ba707d2d83b05aa
I'll need to double check if there's anything else before closing

**Comment by pdxiv** [comment]
I'm fairly confident that this is fixed now, along with all other typos in commit 28f94f2ebf1f3783924d9fb14544844dfb26a5e2
