### ISSUE TITLE
Fail to load "other adventures" from various authors

### ISSUE THREAD

**Issue by pdxiv** [pdxiv/PerlScott#9]
The PerlScott interpreter should be more tolerant with input files. The following adventure files currently fail to load, for various reasons:
```
  Miner's Adventure, by Bruce Hansen (MINER.DAT)
  James Bond Adventure (author unknown) (BOND.DAT)
  Burglar's Adventure, by Bruce Hansen (BURGLAR.DAT)
  Romulan Adventure, by Jim Veneskey (ROMULAN.DAT)
  Top Secret Adventure, by Jim Veneskey (SECRET.DAT)
  Gamma World, by Jim Veneskey (GAMMA.DAT)
  Marooned, by Kim Watt (MAROONED.DAT)
  Undersea Conquest part I, by Marc Mandel (CONQUEST.DAT)
```
Reasons for failure:
* Newline characters are 0x0D (Apple II?), where PerlScott expects 0x0A
* Line 873, can't handle cases where there is no space between object name and the object's room number
* Line 902, fails for unknown reasons with `CONQUEST.DAT` and `BURGLAR.DAT`

**Comment by auraes** [comment]
Some game databases are not clean. They could be loaded, modified, adapted and saved on different systems, changing the original values.
In character strings, the line feed can therefore be CR, LF or CRLF.

For objects you can have:
"A large fountain pen/PEN/"3
or
"A large fountain pen/PEN/" 3
or
"A large fountain pen/PEN/"
3
or
"A large fountain pen/PEN/"

3

You can have empty lines everywhere. Only those in the strings are significant.

**Comment by pdxiv** [comment]
That's a good point. What i think i'll do, is to simplfy the current loading method by just reading the game data into a giant string and then regexing different types of fields out of that. It's a bit of a large-ish overhaul, but it'll make the code simpler (aside from the regex, of course, where simplicity is a matter of opinion). This will take the code one step further away from the original BASIC though.

**Comment by auraes** [comment]
Can't you read the database in binary mode, byte by byte, and clean it up to put it in a character string or temporary file? I was doing this to decompile this games.

**Comment by pdxiv** [comment]
That is, sort of what i'm doing with regular expressions. It's just a compact way of extracting chunks of characters from a string according to some rules. With this, i may not even need to care about what newline encoding the data file uses. For example:

The following will find and extract fields from any possible legitimate room entry from a data file:
`\s*"([^"]*)"\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)`

The following will find and extract fields from any possible legitimate object entry:
`\s*"([^"]*?)(?:/([^/]+)/)?"\s*(-?\d+)`

The following will get and extract data from a verb or a noun:
`\s*"(\*?\S*?)"`

The following will get and extract data from an action comment:
`\s*"([^"]*)"`

The following will get and extract a numerical value:
`\s*(-?\d+)`

**Comment by auraes** [comment]
I don't understand much about all this but it has been very good and effective! 
You just have to be careful in the character strings not to break the text formatting.

**Comment by pdxiv** [comment]
What we need, to handle the newline issue (at least in text strings, such as messages), is some way to automatically find each possible newline, and then replace that with whatever newline convention is used by the current computer platform. In Perl, we can get this with the predefined variable $INPUT_RECORD_SEPARATOR. I'm thinking that I can do that with a slightly complex regexp as follows:

There are three possible newline encodings:
```
\x0a     (unix)
\x0d     (apple)
\x0d\x0a (dos)
```

unix newline can not be preceeded by `\x0d`
unix newline can not be followed by `\x0d`
`(?<![\x0d])[\x0a](?![\x0d])`

apple newline can not be preceeded by `\x0a`
apple newline can not be followed by `\x0a`
`(?<![\x0a])[\x0d](?![\x0a])`

dos newline can not be preceeded by `\x0d`
dos newline can not be followed by `\x0a`
`(?<![\x0d])[\x0d][\x0a](?![\x0a])`

Putting these three together, gives the following pattern:
`(?<![\x0d])[\x0a](?![\x0d])|(?<![\x0a])[\x0d](?![\x0a])|(?<![\x0d])[\x0d][\x0a](?![\x0a])`

The last one looks pretty intimidating, and is fairly unreadable, but it's okay to treat regular expressions as "write only code" in this case.

**Comment by pdxiv** [comment]
So, here is some working test code for handling the newlines at least:
```perl
#!/usr/bin/perl
use strict;
use warnings;
use Readonly;
use Carp;
use English qw( -no_match_vars );
our $VERSION = '1.0.0';

# my $game_file = 'BOND.DAT';
# my $game_file = 'BURGLAR.DAT';
my $game_file = 'MINER.DAT';

open my $handle, '<', $game_file or croak;
my $file_content = do { local $INPUT_RECORD_SEPARATOR; <$handle> };
close $handle or croak;

# Define pattern for finding three types of newlines
my $unix            = qr/(?<![\x0d])[\x0a](?![\x0d])/msx;
my $apple           = qr/(?<![\x0a])[\x0d](?![\x0a])/msx;
my $dos             = qr/(?<![\x0d])[\x0d][\x0a](?![\x0a])/msx;
my $newline_pattern = qr/$unix|$apple|$dos/msx;

# Replace newline in file with whatever the current system uses
$file_content =~ s/$newline_pattern/$INPUT_RECORD_SEPARATOR/msxg;

print $file_content;
```

**Comment by pdxiv** [comment]
Found another problem with the following:
```
James Bond Adventure (author unknown) (BOND.DAT)
Gamma World, by Jim Veneskey (GAMMA.DAT)
Top Secret Adventure, by Jim Veneskey (SECRET.DAT)
```
In `BOND.DAT`, the header says that there are 55 rooms, but there are only 54 rooms declared further down in the file. In `GAMMA.DAT`, the ratio is 23/30. For `SECRET.DAT` the ratio is 33/40. The question is, if this should be tolerated, or if the interpreter should just die. Not quite sure how to proceed.

It would be interesting to know which approach Jim Veneskey used to create these, and since `BOND.DAT` also has this problem, if it was created by him, or someone using the same system. (Or if it's simply a matter of an erroneous conversion from a different format.)

**Comment by auraes** [comment]
I'll look for James Bond Adventure, I know the game well, I fixed it and made the solution.
http://www.solutionarchive.com/game/id%2C5670/James+Bond+Adventure.html

**Comment by auraes** [comment]
For James Bond Adventure, you must be mistaken. The header says there are 55 rooms (from 0 to 55, so 56 rooms). When I decompiled the database, I had 56 rooms. Room 55 (the 56th),  is dead room: "*I'M DEAD!".
All works fine.

**Comment by pdxiv** [comment]
I tried `advent_fixed.qe` and it also had the 54/55 object thing. I'll try and verify some more, if i missed something in my code.

**Comment by auraes** [comment]
Gamma World is correct. You must have a problem in your code.

**Comment by auraes** [comment]
There's a big problem with Marooned database (by Kim Watt , MAROONED.DAT):
the verb GET is at position 9 in the table instead of the required position 10, and DROP is at position 16 instead of 18. There are synonyms at 10 and 18, but this does not work with the TRS-80 interpreter.
It is impossible to take or drop objects if there's no action entries for that. The game is unplayable.
I need to see if I can find any other files from the game.

**Comment by pdxiv** [comment]
Thanks for the help and the additional information!

The reason for not being able to load those three games properly, was that i didn't recognize verb and noun data that contained spaces. That resulted in reading too few words in, and when it was time to read the room data, the read order was not synchronized.

I'm sure more amusing peculiarities lie ahead with these game files :smile:

**Comment by pdxiv** [comment]
Fixed with new file loading routine in commit 6e2db5757da5029a4f77bc929db580d14e414217 that seems to fix the problems with loading the above 8 game database files.
